[DEFAULT]
pristine-tar = True
debian-branch = debian-unstable
upstream-branch = upstream-unstable
upstream-vcs-tag = %(version)s

[import-orig]
postimport = dch -v%(version)s New upstream release; git add debian/changelog; debcommit
